name: dthr_sync
description: >
  Pacote Flutter para sincronizar e manter um relógio local baseado na data/hora de uma API externa, com persistência e fallback offline.
version: 0.1.0
homepage: https://github.com/seuusuario/my_dthr_clock
repository: https://github.com/seuusuario/my_dthr_clock
issue_tracker: https://github.com/seuusuario/my_dthr_clock/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  # get_it: ^8.0.3
  http: ^1.4.0
  # intl: ^0.18.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  test: ^1.24.0
# flutter:
# Este pacote não contém nenhum recurso específico (ex: assets ou fonts).
